name: popular_movies
description: "Test project for Kueski by Jorge Gámez."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  bloc: ^8.1.4
  intl: ^0.20.1
  infinite_scroll_pagination: ^4.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
